name: Run Tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    ### Services needed for the tests
    # Uncomment if needed
    # services:
    #   mongodb:
    #     image: mongo
    #     ports:
    #       - 27017:27017

    ### Steps to run the tests
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e '.[history,storage,chat,retrieval]'
        pip install pytest  # Install pytest

    - name: Run tests with pytest
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        pytest tests  # Run tests using pytest
